version: '3'
services:
  db:
    image: postgres:10.3-alpine
    container_name: postgres01
  api:
    build: .
    container_name: api01
    depends_on:
      - db
      - aerospike-server
    volumes:
      - ./project:/var/www
    expose:
      - "8000:80"
    restart: always
    command:
      - /etc/init.d/fcgiwrap start
      - nginx -g 'daemon off;'
